
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-java
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-java
  template:
    metadata:
      labels:
        app: myapp-java
    spec:
      containers:
        - name: myapp-java
          image: servitekcloud.azurecr.io/myapp-java:latest  # ser√° sustituida por el tag SHA
          ports:
            - containerPort: 8080