apiVersion: v1
kind: Service
metadata:
  name: myapp-java-service
  namespace: default
spec:
  selector:
    app: myapp-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
