name: Build & Sonar - Default Branch
#on:
#  push:
#    branches: [ "master" ]   # Cambia a "master" si esa es tu default
#  workflow_dispatch:        # Permite lanzarlo manualmente por si no hay push
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on the source code
    steps:
      - uses: actions/checkout@v4
      - name: setup java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Sonar Analysis with cloud
        run:  mvn -B verify sonar:sonar -Dsonar.projectKey=developer1-servitekconsulting_api-tesis-prueba -Dsonar.organization=developer1-servitekconsulting -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  security:
    runs-on: ubuntu-latest
    needs: build
    name: Run the SCA scan on the source code (Snyk Open Source)
    steps:
      - uses: actions/checkout@v4
      # Asegura que el wrapper sea ejecutable (muy importante en Linux)
      - name: Make mvnw executable
        run: chmod +x mvnw

      # Pre-check recomendado por Snyk: ejecuta el wrapper en la raíz del proyecto
      - name: Maven dependency tree (dot) pre-check using mvnw
        run: ./mvnw -B dependency:tree -DoutputType=dot

      # Acción de Snyk con Maven/JDK 17 dentro del contenedor
      - name: Run Snyk to check for vulnerabilities (Maven 3 + JDK 17)
        uses: snyk/actions/maven-3-jdk-17@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file=pom.xml

  zap_scan:
    runs-on: ubuntu-latest
    needs: security
    permissions:
      contents: read
      issues: write     # permite crear Issues con los hallazgos del ZAP

    name: Run DAST scan on the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://4.152.197.247/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'